services:
  php:
    image: php:7.4-fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    ports:
      - 1664:9000

  consumer:
    image: php:7.4-fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
