services:
  php:
    image: php:7.4-fpm
    volumes:
      - ./src:/var/www/html
    ports:
      - 1664:9000

  consumer:
    image: php:7.4-fpm
    volumes:
      - ./src:/var/www/html

  nginx:
    image: nginx:1.21-alpine
    ports:
      - 8050:80
      - 7777:80
